### ISSUE TITLE
Set up API using fastapi

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/AppleFoliarAI#4]
[Reference](https://fastapi.tiangolo.com/)

**Comment by Ananya-Misra** [comment]
I would like to give this issue a try. Please assign this to me.

**Comment by Ananya-Misra** [comment]
@phreakyphoenix  Can you please guide me as to how can I run this project on my computer?

**Comment by smaranjitghose** [comment]
This was assigned to you 13 days ago and now if you request us help with basic set up that is not possible

**Comment by mayank-wadhwa-git** [comment]
I would like to give this issue a try under DCP.

**Comment by smaranjitghose** [comment]
Assigned for 3 days

**Comment by mayank-wadhwa-git** [comment]
ok

**Comment by mayank-wadhwa-git** [comment]
@smaranjitghose Can you please guide me as to how can I run this project on my computer?

**Comment by smaranjitghose** [comment]
In any other situation, I would have happily helped.
But if you are requesting for getting assigned to an issue, the primary assumption is that you had sorted this out already.
