### ISSUE TITLE
Add Let'sGrowMore logo under 'Open Source Program' section

### ISSUE THREAD

**Issue by Ayan-thecodeking** [smaranjitghose/AppleFoliarAI#7]
Since this project is part of LGMSOC . I think it's good idea to showcase it in README.md file under Open Source Program section .
I will like to work on this issue under LGMSOC if maintainers agree @smaranjitghose

**Comment by phreakyphoenix** [comment]
Looks good to me, Please add it after `our hard-working project maintainers` and before `our valuable contributors`. The logo should have the same dimensions as the contributors' round icons and should be visually appealing and not break anything else. @Ayan-thecodeking you are assigned this for three days, ie. till 11:59 pm IST on Saturday. Good luck!

**Comment by Ayan-thecodeking** [comment]
> Looks good to me, Please add it after `our hard-working project maintainers` and before `our valuable contributors`. The logo should have the same dimensions as the contributors' round icons and should be visually appealing and not break anything else. @Ayan-thecodeking you are assigned this for three days, ie. till 11:59 pm IST on Saturday. Good luck!

Ok thanks :)
