### ISSUE TITLE
add some badges to README

### ISSUE THREAD

**Issue by Umesh-01** [smaranjitghose/AppleFoliarAI#9]
### Description
add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

### Solution
**I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.**

![image](https://user-images.githubusercontent.com/83420185/123467782-84278200-d60e-11eb-9f51-f4c231e82609.png)

### Work under/as
- [x] LGMSOC
- [x] Contributor

**Comment by Umesh-01** [comment]
@phreakyphoenix @smaranjitghose should I work on this??

I will add badges like this

![image](https://user-images.githubusercontent.com/83420185/123469139-4cb9d500-d610-11eb-9631-dc0c6b37b08c.png)

**Comment by phreakyphoenix** [comment]
Hi @Umesh-01, this won't be necessary right now. Thanks for your interest.
